
bot_name: 优菈   #机器人名字，训练功能会用到
start_tip: 优菈上班了,今天又是充满干劲的一天~   #上班提示语  
close_tip: 优菈去找安柏玩了，再见~      #下班提示语
start_order: '#优菈上班'     #机器人上班指令  如需修改，将引号里面的东西换成自己的
close_order: '#优菈下班'     #机器人下班指令。如需修改，将引号里面的东西换成自己的

poke_switch: false #戳一戳开关,默认false关闭，改成true开启