poked_words: #被戳时回复
  - '可不可以不要戳优菈啦~'
  - '别戳了可以嘛'
  - '要戳坏掉了>_<，呜呜呜' 
  - '你老是欺负我，我要告诉安柏去'
  - '别戳了!!!'
  - '再戳优菈就要坏掉了呀'
  - '不可以，不可以，不可以！戳疼了！'
  - '这可是很失礼的'
  - '这个仇我记下了'

poke_words: #戳别人时发送
  - '你刚刚是不是戳我了，我要戳回去，哼！！！'
  - '还击~'